name: Build and Deploy to Google Cloud Storage

on:
  push:
    branches:
    - main

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node.js (NPM)
      uses: actions/setup-node@master
      with:
        node-version: '12.x'

    - name: Use cached node_modules
      uses: actions/cache@master
      with:
        path: node_modules
        key: nodeModules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          nodeModules-

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      env:
        CI: true

    - name: Build Development
      run: yarn build

    - name: Archive Production Artifact
      uses: actions/upload-artifact@main
      with:
        name: build
        path: build

    - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        gsutil -m rsync -R dist gs://$GCS_BUCKET